"use client";
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ehFdqDW0hLY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { motion } from "framer-motion"
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"

export function Header() {
  return (
    (<motion.header
      className="bg-background dark:bg-background sticky top-0 z-40 w-full border-b border-b-muted"
        initial={{ y: -100, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}>
      <div className="container flex h-16 items-center justify-between px-4 md:px-6 border-opacity-40">
        <Link
          href="#"
          className="flex items-center gap-2 text-lg font-semibold"
          prefetch={false}>
          <CodeIcon className="h-6 w-6" />
          <span>Nick Giuliani</span>
        </Link>
        <nav className="hidden items-center gap-6 md:flex">
          <Link
            href="#"
            className="text-sm font-medium transition-colors hover:underline"
            prefetch={false}>
            Projects
          </Link>
          <Link
            href="#"
            className="text-sm font-medium transition-colors hover:underline"
            prefetch={false}>
            Contact
          </Link>
          <Link
            href="#"
            className="text-sm font-medium transition-colors hover:underline"
            prefetch={false}>
            About
          </Link>
          <Link
            href="#"
            className="text-sm font-medium transition-colors hover:underline"
            prefetch={false}>
            Experience
          </Link>
        </nav>
        <Sheet>
          <SheetTrigger asChild>
            <Button variant="outline" size="icon" className="md:hidden">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle navigation</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="left" className="md:hidden">
            <div className="grid gap-4 p-4">
              <Link
                href="#"
                className="text-sm font-medium transition-colors hover:text-primary"
                prefetch={false}>
                Projects
              </Link>
              <Link
                href="#"
                className="text-sm font-medium transition-colors hover:text-primary"
                prefetch={false}>
                Contact
              </Link>
              <Link
                href="#"
                className="text-sm font-medium transition-colors hover:text-primary"
                prefetch={false}>
                About
              </Link>
              <Link
                href="#"
                className="text-sm font-medium transition-colors hover:text-primary"
                prefetch={false}>
                Experience
              </Link>
            </div>
          </SheetContent>
        </Sheet>
      </div>
    </motion.header>)
  );
}

function CodeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
